name: Setup Node JS
on:

jobs:
  build:
    runs-on: ${{ vars.JOB_RUNNERS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Install dependencies
        run: npm ci

      - name: Run npm tests
        run: npm test
        if: github.ref == 'refs/heads/master'

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}