name: External Events
on:
  repository_dispatch:
    types: [build] # Limit events send keywords [build, test]

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.env }}