name: Runner Info
on: [push]

jobs:
  info:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Runner info
        uses: devops-actions/load-runner-info@v1.0.6
        id: load-runner-info-org
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.organization }}