name: Simple Action Slack Joke
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send a joke on Slake
        uses: ./.github/actions/slack-joke
        id: slack-joke
        with:
          slack_username: 'howcoolpl'
          upload_joke: true
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Displaying joke output
        run: echo '${{ steps.slack-joke.outputs.joke }}'