name: Simple Action Slack PHP
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send a Slack Message
        uses: ./.github/actions/slack-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Stack